name: Github Workflow for Lambda project
run-name: Workflow number ${{github.run_number}}

on:
  push:
    branches:
      - main

jobs:
  #? Job - 1
  frontend_setup:
    runs-on: ubuntu-latest
    name: A job is to build a frontend project

    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Node JS Setup
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Setup QEMU # Optional
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PWD}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install dependencies and Build the project
        run: |
          npm install
          npm run build

      - name: Dockerize and PUSH the frontend project to DOCKER HUB
        run: |
          docker build . --file Dockerfile --tag fradriks/serverless-frontend:${{github.sha}}
          docker push fradriks/serverless-frontend:${{github.sha}}

      - name: Create S3 bucket (if not exists)
        run: |
          if ! aws s3api head-bucket --bucket ${{ secrets.S3_BUCKET_NAME }} 2>/dev/null; then
          aws s3api create-bucket --bucket ${{ secrets.S3_BUCKET_NAME }} --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
          aws s3api put-bucket-policy --bucket ${{ secrets.S3_BUCKET_NAME }} --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::'${{ secrets.S3_BUCKET_NAME }}'/*"
              }
            ]
          }'
      - name: Sync build files to S3 bucket
        run: |
          aws s3 rm s3://${{secrets.S3_BUCKET_NAME}} --recursive
          aws s3 sync .next/static s3://${{secrets.S3_BUCKET_NAME}}/_next/static
          aws s3 sync out/ s3://${{secrets.S3_BUCKET_NAME}} --delete

    needs: backend_setup

  #? Job - 2
  backend_setup:
    runs-on: ubuntu-latest
    name: A job is to build a backend project

    defaults:
      run:
        shell: bash
        working-directory: ./server

    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Node JS Setup
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Setup QEMU # Optional
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PWD}}

      - name: Install dependencies and Linting the project
        run: |
          npm install
          npm run lint

      - name: Dockerize and PUSH the backend project to DOCKER HUB
        run: |
          docker build . --file Dockerfile --tag fradriks/serverless-backend:${{github.sha}}
          docker push fradriks/serverless-backend:${{github.sha}}
